spring.application.name=demo
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/orm_milch
spring.datasource.username=farrenkopf
spring.datasource.password= password
spring.datasource.driver-class-name=org.postgresql.Driver